export const WMO_CODES = {
  0:  { day: { description: "Cielo despejado",              icon: "01d" }, night: { description: "Cielo despejado",              icon: "01n" } },
  1:  { day: { description: "Mayormente despejado",         icon: "01d" }, night: { description: "Mayormente despejado",         icon: "01n" } },
  2:  { day: { description: "Parcialmente nublado",         icon: "02d" }, night: { description: "Parcialmente nublado",         icon: "02n" } },
  3:  { day: { description: "Nublado",                      icon: "04d" }, night: { description: "Nublado",                      icon: "04n" } },
  45: { day: { description: "Niebla",                       icon: "50d" }, night: { description: "Niebla",                       icon: "50n" } },
  48: { day: { description: "Niebla con escarcha",          icon: "50d" }, night: { description: "Niebla con escarcha",          icon: "50n" } },
  51: { day: { description: "Llovizna ligera",              icon: "09d" }, night: { description: "Llovizna ligera",              icon: "09n" } },
  53: { day: { description: "Llovizna moderada",            icon: "09d" }, night: { description: "Llovizna moderada",            icon: "09n" } },
  55: { day: { description: "Llovizna intensa",             icon: "09d" }, night: { description: "Llovizna intensa",             icon: "09n" } },
  56: { day: { description: "Llovizna engelante ligera",    icon: "09d" }, night: { description: "Llovizna engelante ligera",    icon: "09n" } },
  57: { day: { description: "Llovizna engelante densa",     icon: "09d" }, night: { description: "Llovizna engelante densa",     icon: "09n" } },
  61: { day: { description: "Lluvia ligera",                icon: "10d" }, night: { description: "Lluvia ligera",                icon: "10n" } },
  63: { day: { description: "Lluvia moderada",              icon: "10d" }, night: { description: "Lluvia moderada",              icon: "10n" } },
  65: { day: { description: "Lluvia intensa",               icon: "10d" }, night: { description: "Lluvia intensa",               icon: "10n" } },
  66: { day: { description: "Lluvia engelante ligera",      icon: "13d" }, night: { description: "Lluvia engelante ligera",      icon: "13n" } },
  67: { day: { description: "Lluvia engelante intensa",     icon: "13d" }, night: { description: "Lluvia engelante intensa",     icon: "13n" } },
  71: { day: { description: "Nieve ligera",                 icon: "13d" }, night: { description: "Nieve ligera",                 icon: "13n" } },
  73: { day: { description: "Nieve moderada",               icon: "13d" }, night: { description: "Nieve moderada",               icon: "13n" } },
  75: { day: { description: "Nieve intensa",                icon: "13d" }, night: { description: "Nieve intensa",                icon: "13n" } },
  77: { day: { description: "Granizo menudo",               icon: "13d" }, night: { description: "Granizo menudo",               icon: "13n" } },
  80: { day: { description: "Chubascos ligeros",            icon: "09d" }, night: { description: "Chubascos ligeros",            icon: "09n" } },
  81: { day: { description: "Chubascos moderados",          icon: "09d" }, night: { description: "Chubascos moderados",          icon: "09n" } },
  82: { day: { description: "Chubascos intensos",           icon: "09d" }, night: { description: "Chubascos intensos",           icon: "09n" } },
  85: { day: { description: "Chubascos de nieve ligeros",   icon: "13d" }, night: { description: "Chubascos de nieve ligeros",   icon: "13n" } },
  86: { day: { description: "Chubascos de nieve intensos",  icon: "13d" }, night: { description: "Chubascos de nieve intensos",  icon: "13n" } },
  95: { day: { description: "Tormenta eléctrica",           icon: "11d" }, night: { description: "Tormenta eléctrica",           icon: "11n" } },
  96: { day: { description: "Tormenta con granizo ligero",  icon: "11d" }, night: { description: "Tormenta con granizo ligero",  icon: "11n" } },
  99: { day: { description: "Tormenta con granizo intenso", icon: "11d" }, night: { description: "Tormenta con granizo intenso", icon: "11n" } },
};
